{{- if not (has "alloy" .Values.applicationBlacklist) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject }}
  destination:
    namespace: alloy
    server: {{ .Values.server }}
  source:
    path: alloy
    repoURL: {{ .Values.argoRepo }}
    targetRevision: {{ .Values.argoRepoBranch }}
    project: {{ .Values.argoProject }}
    helm:
      valueFiles:
        - values.yaml
      values: |
        alloy:
          mounts:
            varlog: true
          extraPorts:
            - name: otlp-grpc
              port: 4317
              targetPort: 4317
              hostPort: 4317
              protocol: TCP
            - name: otlp-http
              port: 4318
              targetPort: 4318
              hostPort: 4318
              protocol: TCP
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
